/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gr2_final.vistas;

import gr2_final.accesoadatos.ClienteData;
import gr2_final.entidades.Cliente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KEVIN
 */
public class ClienteVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClienteVista
     */
    private DefaultTableModel modelo;

    public ClienteVista() {
        initComponents();

        modelo = new DefaultTableModel();
        armarCabecera();
    }

    //crea/modifica la tabla
    private void armarCabecera() {
        modelo.addColumn("Código");
        modelo.addColumn("DNI");
        modelo.addColumn("Nombre Completo");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Edad");
        modelo.addColumn("Afecciones");
        modelo.addColumn("Estado");

        jTTablaClientes.setModel(modelo);
    }

    private void borrarFilasTabla() {
        int filas = modelo.getRowCount() - 1;
        for (int i = filas; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTNombreCompleto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTDNI = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTnTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTEdad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTAfecciones = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTablaClientes = new javax.swing.JTable();
        jBBuscar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jCEstado = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jTDniBuscar = new javax.swing.JTextField();
        jBNuevoCliente = new javax.swing.JButton();
        jBListarClientes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("Código:");

        jTCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCodigoActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre completo:");

        jLabel4.setText("Dni:");

        jTDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDNIActionPerformed(evt);
            }
        });

        jLabel5.setText("Teléfono:");

        jLabel6.setText("Edad:");

        jLabel7.setText("Afecciones:");

        jTAfecciones.setForeground(new java.awt.Color(153, 153, 153));
        jTAfecciones.setText("Ej : problemas de la columna");

        jTTablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre Completo", "DNI", "Telefono", "Edad", "Afecciones", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTTablaClientes);

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        jLabel8.setText("Estado:");

        jLabel9.setText("Buscar por DNI :");

        jTDniBuscar.setForeground(new java.awt.Color(153, 153, 153));

        jBNuevoCliente.setText("Nuevo");
        jBNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoClienteActionPerformed(evt);
            }
        });

        jBListarClientes.setText("Listar Clientes Existentes");
        jBListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTCodigo)
                                            .addComponent(jTAfecciones, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                            .addComponent(jTEdad, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTnTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTDNI, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTNombreCompleto))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jBGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jBModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jBEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jBLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jBBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jBNuevoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jTDniBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBListarClientes)
                .addGap(329, 329, 329))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBNuevoCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGuardar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBModificar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTnTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEliminar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLimpiar))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTAfecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCEstado)
                    .addComponent(jLabel8))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTDniBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBBuscar))))
                .addGap(18, 38, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBListarClientes)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("CLIENTE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDNIActionPerformed

    private void jTCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCodigoActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        try {
            ClienteData clienteData = new ClienteData();

            int dni = Integer.parseInt(jTDNI.getText().trim());
            String nombre = jTNombreCompleto.getText().trim();
            String telefono = jTnTelefono.getText().trim();
            int edad = Integer.parseInt(jTEdad.getText().trim());
            String afecciones = jTAfecciones.getText().trim();
            boolean estado = jCEstado.isSelected();

            Cliente cliente = new Cliente(dni, nombre, telefono, edad, afecciones, estado);

            clienteData.guardarCliente(cliente);

            jTCodigo.setText(String.valueOf(cliente.getCodCli()));

            jBModificar.setEnabled(true);
            jBEliminar.setEnabled(true);
            jBBuscar.setEnabled(true);

            jBGuardar.setEnabled(false);

            jBNuevoCliente.setEnabled(true);

            jTCodigo.setEditable(false);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese números válidos (DNI, Edad).");
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoClienteActionPerformed
        jTCodigo.setText("");
        jTDNI.setText("");
        jTNombreCompleto.setText("");
        jTnTelefono.setText("");
        jTEdad.setText("");
        jTAfecciones.setText("");
        jCEstado.setSelected(false);

        jBModificar.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBBuscar.setEnabled(false);
        jBGuardar.setEnabled(true);

        jTCodigo.setEditable(false);
    }//GEN-LAST:event_jBNuevoClienteActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        try {
            int dni = Integer.parseInt(jTDniBuscar.getText().trim());

            ClienteData clienteData = new ClienteData();
            Cliente cliente = clienteData.buscarClientePorDni(dni);

            if (cliente == null) {
                JOptionPane.showMessageDialog(this, "No se encontró el cliente");
                return;
            }
            jTCodigo.setText(String.valueOf(cliente.getCodCli()));
            jTDNI.setText(String.valueOf(cliente.getDni()));
            jTNombreCompleto.setText(cliente.getNombreCompleto());
            jTnTelefono.setText(cliente.getTelefono());
            jTEdad.setText(String.valueOf(cliente.getEdad()));
            jTAfecciones.setText(cliente.getAfecciones());
            jCEstado.setSelected(cliente.isEstado());
            //bloquear/desabilitar botones
            jBModificar.setEnabled(true);
            jBEliminar.setEnabled(true);
            jBGuardar.setEnabled(false);
            jBNuevoCliente.setEnabled(true);

            jTCodigo.setEditable(false);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un DNI válido.");
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        try {

            ClienteData clienteData = new ClienteData();

            int codCli = Integer.parseInt(jTCodigo.getText().trim());
            int dni = Integer.parseInt(jTDNI.getText().trim());
            String nombre = jTNombreCompleto.getText().trim();
            String telefono = jTnTelefono.getText().trim();
            int edad = Integer.parseInt(jTEdad.getText().trim());
            String afecciones = jTAfecciones.getText().trim();
            boolean estado = jCEstado.isSelected();

            if (nombre.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.");
                return;
            }
            if (telefono.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El teléfono no puede estar vacío.");
                return;
            }

            Cliente cliente = new Cliente();
            cliente.setCodCli(codCli);
            cliente.setDni(dni);
            cliente.setNombreCompleto(nombre);
            cliente.setTelefono(telefono);
            cliente.setEdad(edad);
            cliente.setAfecciones(afecciones);
            cliente.setEstado(estado);

            clienteData.modificarCliente(cliente);

            jBGuardar.setEnabled(false);
            jBModificar.setEnabled(true);
            jBEliminar.setEnabled(true);
            jBBuscar.setEnabled(true);
            jBNuevoCliente.setEnabled(true);

            jTCodigo.setEditable(false);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Verifique los campos numéricos (Codigo, DNI, Edad).");
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        try {

            if (jTCodigo.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Primero busque un cliente antes de eliminar.");
                return;
            }

            // Obtener el código del cliente
            int codCli = Integer.parseInt(jTCodigo.getText().trim());

            // Confirmación
            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "¿Seguro que desea eliminar este cliente?",
                    "Confirmación",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            ClienteData clienteData = new ClienteData();
            clienteData.borradoLogicoCliente(codCli);

            limpiarCampos();

            // nota para los pibes , aca desabilito estos botones pq no podes guardar , modificar , eliminar si los campos estan vacios
            // si podes buscar o crear un cliente nuevo
            jBGuardar.setEnabled(false);
            jBModificar.setEnabled(false);
            jBEliminar.setEnabled(false);
            jBNuevoCliente.setEnabled(true);
            jBBuscar.setEnabled(true);

            jTCodigo.setEditable(false);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Código inválido. Verifique.");
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListarClientesActionPerformed
        ClienteData cd = new ClienteData();
        List<Cliente> lista = cd.listaClientes();

        borrarFilasTabla();

        for (Cliente c : lista) {
            modelo.addRow(new Object[]{
                c.getCodCli(),
                c.getDni(),
                c.getNombreCompleto(),
                c.getTelefono(),
                c.getEdad(),
                c.getAfecciones(),
                c.isEstado() ? "Activo" : "Inactivo"
            });
        }
    }//GEN-LAST:event_jBListarClientesActionPerformed

    private void limpiarCampos() {
        jTCodigo.setText("");
        jTNombreCompleto.setText("");
        jTDNI.setText("");
        jTnTelefono.setText("");
        jTEdad.setText("");
        jTAfecciones.setText("");
        jCEstado.setSelected(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBListarClientes;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBNuevoCliente;
    private javax.swing.JCheckBox jCEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTAfecciones;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextField jTDNI;
    private javax.swing.JTextField jTDniBuscar;
    private javax.swing.JTextField jTEdad;
    private javax.swing.JTextField jTNombreCompleto;
    private javax.swing.JTable jTTablaClientes;
    private javax.swing.JTextField jTnTelefono;
    // End of variables declaration//GEN-END:variables
}
