/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gr2_final.vistas;

import gr2_final.entidades.Consultorio;
import gr2_final.accesoadatos.ConsultorioData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KEVIN
 */
public class ConsultorioVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultorioVista
     */
    private DefaultTableModel modelo;

    public ConsultorioVista() {
        initComponents();
        modelo = new DefaultTableModel();
        armarCabecera();
        cargarUsos();
        cargarfiltro();
        llenarFiltro();
    }

    private void cargarfiltro() {
        jCFiltros.addItem("Todos");
        jCFiltros.addItem("Aptos");
        jCFiltros.addItem("Usos");
    }

    private void cargarUsos() {
        jCUsos.addItem("facial");
        jCUsos.addItem("corporal");
        jCUsos.addItem("relajacion");
        jCUsos.addItem("estetico");
    }

    private void llenarFiltro() {
        jCUsosFiltro.addItem("Facial");
        jCUsosFiltro.addItem("Estética");
        jCUsosFiltro.addItem("relajacion");
        jCUsosFiltro.addItem("estetico");

    }

    private void armarCabecera() {
        modelo.addColumn("Consultorio N°");
        modelo.addColumn("Usos");
        modelo.addColumn("Equipamiento");
        modelo.addColumn("Apto");
        jTListar.setModel(modelo);
    }

    private void borrarFilasTabla() {
        int filas = modelo.getRowCount() - 1;
        for (int i = filas; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtNConsultorio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCUsos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtEquipamiento = new javax.swing.JTextField();
        jCApto = new javax.swing.JCheckBox();
        jBBuscar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBNuevo = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTListar = new javax.swing.JTable();
        jCFiltros = new javax.swing.JComboBox<>();
        jBListar = new javax.swing.JButton();
        jCUsosFiltro = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("CONSULTORIO");

        jLabel2.setText("Nro Consultorio:");

        jLabel3.setText("Usos:");

        jLabel4.setText("Equipamiento:");

        jCApto.setText("Apto");

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jLabel5.setText("Buscar consultorio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jBEliminar))
                            .addComponent(jtBuscar))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jCApto, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtNConsultorio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtEquipamiento)
                            .addComponent(jCUsos, 0, 307, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1)))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtNConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCUsos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtEquipamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCApto)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBModificar)
                    .addComponent(jBEliminar)
                    .addComponent(jBNuevo)
                    .addComponent(jBGuardar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar)
                    .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jTListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTListar);

        jCFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCFiltrosActionPerformed(evt);
            }
        });

        jBListar.setText("listar");
        jBListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCUsosFiltro, 0, 304, Short.MAX_VALUE)
                            .addComponent(jCFiltros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addComponent(jBListar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBListar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCUsosFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        jtNConsultorio.setEnabled(false);
        jtNConsultorio.setText("");
        jCUsos.setSelectedIndex(-1);
        jtEquipamiento.setText("");
        jCApto.setSelected(true);

        jBModificar.setEnabled(false);
        jBEliminar.setEnabled(false);

        jBGuardar.setEnabled(true);
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        try {

            if (jCUsos.getSelectedIndex() == -1 || jtEquipamiento.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Complete todos los campos.");
                return;
            }

            String usos = jCUsos.getSelectedItem().toString();
            String equip = jtEquipamiento.getText();
            boolean apto = jCApto.isSelected();

            Consultorio c = new Consultorio();
            c.setUsos(usos);
            c.setEquipamiento(equip);
            c.setApto(apto);

            ConsultorioData cd = new ConsultorioData();
            cd.guardarConsultorio(c);

            jtNConsultorio.setText(String.valueOf(c.getNroConsultorio()));

            jBGuardar.setEnabled(false);
            jBModificar.setEnabled(true);
            jBEliminar.setEnabled(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        try {
            if (jtBuscar.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese un número para buscar.");
                return;
            }

            int nro = Integer.parseInt(jtBuscar.getText());

            ConsultorioData cd = new ConsultorioData();
            Consultorio c = cd.buscarConsultorio(nro);

            if (c != null) {

                jtNConsultorio.setText(String.valueOf(c.getNroConsultorio()));
                jCUsos.setSelectedItem(c.getUsos());
                jtEquipamiento.setText(c.getEquipamiento());
                jCApto.setSelected(c.isApto());

                jtNConsultorio.setEnabled(false);

                jBModificar.setEnabled(true);
                jBEliminar.setEnabled(true);

                jBGuardar.setEnabled(false);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Número inválido.");
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        try {

            if (jtNConsultorio.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Primero busque un consultorio.");
                return;
            }

            int nro = Integer.parseInt(jtNConsultorio.getText());
            String usos = jCUsos.getSelectedItem().toString();
            String equip = jtEquipamiento.getText();
            boolean apto = jCApto.isSelected();

            Consultorio c = new Consultorio(nro, usos, equip, apto);

            ConsultorioData cd = new ConsultorioData();
            cd.modificarConsultorio(c);

            jBGuardar.setEnabled(false);
            jBModificar.setEnabled(true);
            jBEliminar.setEnabled(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al modificar: " + e.getMessage());
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        try {
            if (jtNConsultorio.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Busque un consultorio primero.");
                return;
            }

            int nro = Integer.parseInt(jtNConsultorio.getText());

            ConsultorioData cd = new ConsultorioData();
            cd.borrarConsultorio(nro);

            jtNConsultorio.setText("");
            jCUsos.setSelectedIndex(-1);
            jtEquipamiento.setText("");
            jCApto.setSelected(false);
            jBModificar.setEnabled(false);
            jBEliminar.setEnabled(false);
            jBGuardar.setEnabled(true);

            jtNConsultorio.setEnabled(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar.");
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTListar.getModel();
        modelo.setRowCount(0);

        String opcion = jCFiltros.getSelectedItem().toString();

        ConsultorioData cd = new ConsultorioData();
        List<Consultorio> lista = new ArrayList<>();

        if (opcion.equals("Todos")) {

            lista = cd.listarConsultorios();

        } else if (opcion.equals("Aptos")) {

            lista = cd.listarConsultoriosAptos();

        } else if (opcion.equals("Usos")) {

            String usoSeleccionado = jCUsosFiltro.getSelectedItem().toString();
            lista = cd.listarPorUsos(usoSeleccionado);
        }

        for (Consultorio c : lista) {
            modelo.addRow(new Object[]{
                c.getNroConsultorio(),
                c.getUsos(),
                c.getEquipamiento(),
                c.isApto()
            });
        }
    }//GEN-LAST:event_jBListarActionPerformed

    private void jCFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCFiltrosActionPerformed
        String opcion = jCFiltros.getSelectedItem().toString();

        if (opcion.equals("Usos")) {
            jCUsosFiltro.setEnabled(true);
        } else {
            jCUsosFiltro.setEnabled(false);
        }
    }//GEN-LAST:event_jCFiltrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBListar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JCheckBox jCApto;
    private javax.swing.JComboBox<String> jCFiltros;
    private javax.swing.JComboBox<String> jCUsos;
    private javax.swing.JComboBox<String> jCUsosFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTListar;
    private javax.swing.JTextField jtBuscar;
    private javax.swing.JTextField jtEquipamiento;
    private javax.swing.JTextField jtNConsultorio;
    // End of variables declaration//GEN-END:variables
}
