/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gr2_final.vistas;

import gr2_final.accesoadatos.ClienteData;
import gr2_final.accesoadatos.DiaDeSpaData;
import gr2_final.accesoadatos.MasajistaData;
import gr2_final.entidades.Cliente;
import gr2_final.entidades.DiaDeSpa;
import gr2_final.entidades.Masajista;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KEVIN
 */
public class DiaDeSpaVista extends javax.swing.JInternalFrame {
    
    private DiaDeSpaData dsData = new DiaDeSpaData();
    private ClienteData cData = new ClienteData();
    private MasajistaData mData = new MasajistaData();
    private DefaultTableModel modeloSpa;
    private DefaultTableModel modeloMasajistas;
    
    /**
     * Creates new form DiaDeSpaVista
     */
    public DiaDeSpaVista() {
        initComponents();
       modeloSpa = new DefaultTableModel();
       modeloMasajistas = new DefaultTableModel();
       armarCabeceraSpa();
       armarCabeceraMasajistas();
       cargarClientes();
       cargarHoras();
       cargarTablaGeneralSpa();
    }
    
     private void armarCabeceraSpa() {
        modeloSpa.addColumn("Código");
        modeloSpa.addColumn("Cliente");
        modeloSpa.addColumn("Fecha - Hora");
        modeloSpa.addColumn("Monto");
        modeloSpa.addColumn("Estado");
        jTablaSpa.setModel(modeloSpa);
    }
     
     private void armarCabeceraMasajistas() {
        modeloMasajistas.addColumn("Matrícula");
        modeloMasajistas.addColumn("Nombre");
        modeloMasajistas.addColumn("Especialidad");
        modeloMasajistas.addColumn("Teléfono");
        jTMasajistas.setModel(modeloMasajistas);
    }
    
   private void limpiarTablaMasajistas() {
        modeloMasajistas.setRowCount(0);
    }

    private void cargarClientes() {
        List<Cliente> lista = cData.listaClientes();
        for (Cliente c : lista) {
            jCCliente.addItem(c);
        }
    }
    
     private void cargarHoras() {
        jCHora.removeAllItems();
        for (int h = 8; h <= 21; h++) {
            jCHora.addItem(String.format("%02d:00", h));
        }
    }
    
    private LocalDateTime obtenerFechaHora() {

        Date fecha = jDChoserFechas.getDate();
        if (fecha == null) return null;

        LocalDate f = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        String horaSel = (String) jCHora.getSelectedItem();
        if (horaSel == null) return null;

        LocalTime hora = LocalTime.parse(horaSel);

        return LocalDateTime.of(f, hora);
    }
    
    private void cargarTablaGeneralSpa() {
        modeloSpa.setRowCount(0);
        List<DiaDeSpa> lista = dsData.listarDiasDeSpa();

        for (DiaDeSpa ds : lista) {
            modeloSpa.addRow(new Object[]{
                ds.getCodPack(),
                ds.getCodCli().getNombreCompleto(),
                ds.getFechaHora(),
                ds.getMonto(),
                ds.isEstado() ? "Activo" : "Anulado"
            });
        }
    }
    
     private void limpiarCampos() {
        jTCodigo.setText("");
        jTMonto.setText("");
        jTPreferencias.setText("");
        jDChoserFechas.setDate(null);
        jCHora.setSelectedIndex(-1);
        modeloMasajistas.setRowCount(0);
    }
    
     private void listarMasajistasLibres() {

        limpiarTablaMasajistas();

        LocalDateTime fechaHora = obtenerFechaHora();
        if (fechaHora == null) {
            JOptionPane.showMessageDialog(this, "Seleccione fecha y hora.");
            return;
        }

        Date inicio = Date.from(fechaHora.atZone(ZoneId.systemDefault()).toInstant());
        Date fin = Date.from(fechaHora.plusHours(1).atZone(ZoneId.systemDefault()).toInstant());

        List<Masajista> libres = mData.listarMasajistasLibresEntre(inicio, fin);

        for (Masajista m : libres) {
            modeloMasajistas.addRow(new Object[]{
                m.getMatricula(),
                m.getNombreCompleto(),
                m.getEspecialidad(),
                m.getTelefono()
            });
        }

        if (libres.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay masajistas libres en ese horario.");
        }
    
   
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JTextField();
        jCCliente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTMonto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPreferencias = new javax.swing.JTextArea();
        jCheckActivo = new javax.swing.JCheckBox();
        jBNuevo = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBuscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablaSpa = new javax.swing.JTable();
        jBListarfecha = new javax.swing.JButton();
        jDChoserFechas = new com.toedter.calendar.JDateChooser();
        jCHora = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTMasajistas = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("DIA DE SPA");

        jLabel2.setText("Codigo:");

        jLabel3.setText("Cliente:");

        jLabel4.setText("Fecha y hora:");

        jLabel5.setText("Monto:");

        jLabel6.setText("Preferencias:");

        jTPreferencias.setColumns(20);
        jTPreferencias.setRows(5);
        jScrollPane1.setViewportView(jTPreferencias);

        jCheckActivo.setText("Activo");

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBuscar.setText("Buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        jTablaSpa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTablaSpa);

        jBListarfecha.setText("Listar Masajistas Libres ");
        jBListarfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListarfechaActionPerformed(evt);
            }
        });

        jTMasajistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTMasajistas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckActivo)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCCliente, 0, 195, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jTCodigo)
                            .addComponent(jTMonto)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jDChoserFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane3)
                    .addComponent(jBListarfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBNuevo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jBGuardar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jBModificar)
                        .addComponent(jCHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDChoserFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEliminar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBuscar))
                .addGap(14, 14, 14)
                .addComponent(jCheckActivo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBListarfecha)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
     try {
            LocalDateTime fechaHora = obtenerFechaHora();
            if (fechaHora == null) {
                JOptionPane.showMessageDialog(this, "Seleccione fecha y hora.");
                return;
            }

            DiaDeSpa ds = new DiaDeSpa();
            ds.setCodCli((Cliente) jCCliente.getSelectedItem());
            ds.setFechaHora(fechaHora);
            ds.setPreferencias(jTPreferencias.getText());
            ds.setMonto(Double.parseDouble(jTMonto.getText()));
            ds.setEstado(true);

            dsData.guardarDiaDeSpa(ds);

            JOptionPane.showMessageDialog(this, "Día de Spa guardado.");
            limpiarCampos();
            cargarTablaGeneralSpa();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        try {
            LocalDateTime fechaHora = obtenerFechaHora();
            if (fechaHora == null) {
                JOptionPane.showMessageDialog(this, "Seleccione fecha y hora.");
                return;
            }

            int codigo;
            try {
                codigo = Integer.parseInt(jTCodigo.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Código inválido.");
                return;
            }

            Cliente cli = (Cliente) jCCliente.getSelectedItem();
            if (cli == null) {
                JOptionPane.showMessageDialog(this, "Seleccione un cliente.");
                return;
            }

            DiaDeSpa ds = new DiaDeSpa();
            ds.setCodPack(codigo);
            ds.setCodCli(cli);
            ds.setFechaHora(fechaHora);
            ds.setPreferencias(jTPreferencias.getText());
            ds.setMonto(Double.parseDouble(jTMonto.getText()));
            ds.setEstado(jCheckActivo.isSelected());

            dsData.modificarDiaDeSpa(ds);

            JOptionPane.showMessageDialog(this, "Día de Spa modificado");
            cargarTablaGeneralSpa();

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Monto inválido.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al modificar: " + e.getMessage());
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
         try {
            int codigo = Integer.parseInt(jTCodigo.getText());
            dsData.eliminarDiaDeSpa(codigo);

            JOptionPane.showMessageDialog(this, "Día de Spa eliminado");
            cargarTablaGeneralSpa();

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Código inválido.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
      try {
            int cod = Integer.parseInt(jTCodigo.getText());
            DiaDeSpa ds = dsData.buscarDiaDeSpa(cod);

            if (ds == null) {
                JOptionPane.showMessageDialog(this, "No existe el Día de Spa.");
                return;
            }

            jCCliente.setSelectedItem(ds.getCodCli());
            jTPreferencias.setText(ds.getPreferencias());
            jTMonto.setText(String.valueOf(ds.getMonto()));

            // convertir LocalDateTime a Date para el JDateChooser
            Date fecha = Date.from(ds.getFechaHora().atZone(ZoneId.systemDefault()).toInstant());
            jDChoserFechas.setDate(fecha);

            // cargar hora en combo
            jCHora.setSelectedItem(String.format("%02d:00", ds.getFechaHora().getHour()));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar.");
        }
    }//GEN-LAST:event_jBuscarActionPerformed

    private void jBListarfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListarfechaActionPerformed
      listarMasajistasLibres();

    
    }//GEN-LAST:event_jBListarfechaActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
    jTCodigo.setEditable(false);
        jCCliente.setSelectedIndex(-1);
        jDChoserFechas.setDate(null);
        jCHora.setSelectedIndex(-1);
        jTMonto.setText("");
        jTPreferencias.setText("");
        jBEliminar.setEnabled(false);
        jBModificar.setEnabled(false);
    }//GEN-LAST:event_jBNuevoActionPerformed
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBListarfecha;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBuscar;
    private javax.swing.JComboBox<Cliente> jCCliente;
    private javax.swing.JComboBox<String> jCHora;
    private javax.swing.JCheckBox jCheckActivo;
    private com.toedter.calendar.JDateChooser jDChoserFechas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTable jTMasajistas;
    private javax.swing.JTextField jTMonto;
    private javax.swing.JTextArea jTPreferencias;
    private javax.swing.JTable jTablaSpa;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
