/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gr2_final.vistas;

import gr2_final.accesoadatos.MasajistaData;
import gr2_final.entidades.Masajista;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KEVIN
 */
public class MasajistaVista extends javax.swing.JInternalFrame {

    private MasajistaData mData = new MasajistaData();
    private DefaultTableModel modelo;

    /**
     * Creates new form MasajistaView
     */
    public MasajistaVista() {
        initComponents();
        modelo = new DefaultTableModel();
        armarTabla();
        cargarEspecialidades();
        SeleccionarEspecialidades();
    }

    //jCsEspecialidades
    private void cargarEspecialidades() {
        // Especialidades de masajistas
        cbEspecialidad.addItem("Facial");
        cbEspecialidad.addItem("Corporal");
        cbEspecialidad.addItem("Relajacion");
        cbEspecialidad.addItem("Estetico");
    }

    private void SeleccionarEspecialidades() {
        jCsEspecialidades.addItem("Facial");
        jCsEspecialidades.addItem("Corporal");
        jCsEspecialidades.addItem("Relajacion");
        jCsEspecialidades.addItem("Estetico");
    }

    private void armarTabla() {
        modelo.addColumn("Matricula");
        modelo.addColumn("Nombre");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Especialidad");
        modelo.addColumn("Estado");
        tablaMasajistas.setModel(modelo);
    }

    private void limpiarTabla() {
        modelo.setRowCount(0);
    }

    private void cargarTablaGeneral() {
        limpiarTabla();
        List<Masajista> lista = mData.listarMasajistasActivos();
        mostrarEnTabla(lista);
    }

    private void mostrarEnTabla(List<Masajista> lista) {
        limpiarTabla();
        for (Masajista m : lista) {
            modelo.addRow(new Object[]{
                m.getMatricula(),
                m.getNombreCompleto(),
                m.getTelefono(),
                m.getEspecialidad(),
                m.isEstado() ? "Activo" : "Inactivo"
            });
        }
    }

    private void limpiarCampos() {
        txtMatricula.setText("");
        txtNombreComp.setText("");
        txtTelefono.setText("");
        cbEspecialidad.setSelectedIndex(0);
        jcheckActivo.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreComp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbEspecialidad = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMasajistas = new javax.swing.JTable();
        jBGuardar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jcheckActivo = new javax.swing.JCheckBox();
        jBNuevoMasajista = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtBuscarMatricula = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jBListarTodos = new javax.swing.JButton();
        jBListarPorEspecialidad = new javax.swing.JButton();
        jCsEspecialidades = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText(" MASAJISTA ");

        jLabel2.setText("Matrícula:");

        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre completo:");

        jLabel4.setText("Teléfono");

        jLabel5.setText("Especialidad");

        tablaMasajistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaMasajistas);

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        jcheckActivo.setText("Activo");

        jBNuevoMasajista.setText("Nuevo");
        jBNuevoMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoMasajistaActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jLabel6.setText("Buscar por Matricula");

        jBListarTodos.setText("Listar todos");
        jBListarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListarTodosActionPerformed(evt);
            }
        });

        jBListarPorEspecialidad.setText("Listar por especialidad");
        jBListarPorEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListarPorEspecialidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCsEspecialidades, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcheckActivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbEspecialidad, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreComp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMatricula)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBuscarMatricula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBNuevoMasajista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBListarPorEspecialidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBListarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jBNuevoMasajista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jBGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jBModificar))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jBEliminar))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcheckActivo)
                    .addComponent(jBLimpiar))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscarMatricula)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBListarTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBListarPorEspecialidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCsEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        try {
            if (txtMatricula.getText().isEmpty()
                    || txtNombreComp.getText().isEmpty()
                    || txtTelefono.getText().isEmpty()
                    || cbEspecialidad.getSelectedIndex() == -1) {

                JOptionPane.showMessageDialog(this,
                        "complete todos los campos y seleccione una especialidad.");
                return;
            }

            int matricula = Integer.parseInt(txtMatricula.getText());
            String nombre = txtNombreComp.getText();
            String telefono = txtTelefono.getText();
            //esto decia yo seleccionar el valor de un item del combobox y pasarlo a string
            String especialidad = cbEspecialidad.getSelectedItem().toString();
            boolean estado = jcheckActivo.isSelected();

            // Crear objeto Masajista
            Masajista m = new Masajista(matricula, nombre, telefono, especialidad, estado);

            MasajistaData md = new MasajistaData();
            md.guardarMasajista(m);

            jBGuardar.setEnabled(false);
            jBModificar.setEnabled(true);
            jBEliminar.setEnabled(true);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "ingrese un numero correcto");
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed

        try {
            if (txtMatricula.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Primero debe buscar un masajista por matrícula.");
                return;
            }

            if (txtNombreComp.getText().isEmpty()
                    || txtTelefono.getText().isEmpty()
                    || cbEspecialidad.getSelectedIndex() == -1) {

                JOptionPane.showMessageDialog(this,
                        "Complete todos los campos antes de modificar.");
                return;
            }

            int matricula = Integer.parseInt(txtMatricula.getText());
            String nombre = txtNombreComp.getText();
            String telefono = txtTelefono.getText();
            String especialidad = cbEspecialidad.getSelectedItem().toString();
            boolean estado = jcheckActivo.isSelected();

            Masajista m = new Masajista(matricula, nombre, telefono, especialidad, estado);

            MasajistaData md = new MasajistaData();
            md.modificarMasajista(m);

            JOptionPane.showMessageDialog(this, "Masajista modificado correctamente.");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "El campo Matrícula debe ser un número entero.");
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        try {
            if (txtMatricula.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese matrícula.");
                return;
            }

            int mat = Integer.parseInt(txtMatricula.getText());

            int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro?");
            if (confirm != JOptionPane.YES_NO_OPTION) {
                return;
            }

            MasajistaData md = new MasajistaData();
            md.borrarMasajista(mat);

            JOptionPane.showMessageDialog(this, "Masajista eliminado.");

            // Limpiar los campos
            txtMatricula.setText("");
            txtNombreComp.setText("");
            txtTelefono.setText("");
            cbEspecialidad.setSelectedIndex(-1);
            jcheckActivo.setSelected(false);

            jBGuardar.setEnabled(true);
            jBModificar.setEnabled(false);
            jBEliminar.setEnabled(false);

            cargarTablaGeneral();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Matrícula inválida.");
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jBNuevoMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoMasajistaActionPerformed
        txtMatricula.setText("");
        txtNombreComp.setText("");
        txtTelefono.setText("");
        cbEspecialidad.setSelectedIndex(-1);
        jcheckActivo.setSelected(false);

        jBModificar.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBBuscar.setEnabled(true);
        jBGuardar.setEnabled(true);;
    }//GEN-LAST:event_jBNuevoMasajistaActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        try {
            // Validar que haya matrícula
            if (txtMatricula.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Ingrese un número de matrícula para buscar.");
                return;
            }

            int matricula = Integer.parseInt(txtMatricula.getText());

            MasajistaData md = new MasajistaData();
            Masajista m = md.buscarMasajista(matricula);

            if (m != null) { //m = masajista 
                txtNombreComp.setText(m.getNombreCompleto());
                txtTelefono.setText(m.getTelefono());

                // Seleccionar especialidad en el combo
                cbEspecialidad.setSelectedItem(m.getEspecialidad());

                // Estado activo/inactivo
                jcheckActivo.setSelected(m.isEstado());

                jBGuardar.setEnabled(false);
                jBModificar.setEnabled(true);
                jBEliminar.setEnabled(true);

            } else {
                JOptionPane.showMessageDialog(this,
                        "No existe masajista con esa matrícula.");

                txtNombreComp.setText("");
                txtTelefono.setText("");
                cbEspecialidad.setSelectedIndex(-1);
                jcheckActivo.setSelected(false);

                jBGuardar.setEnabled(true);
                jBModificar.setEnabled(false);
                jBEliminar.setEnabled(false);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "La matrícula debe ser un número entero.");
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBListarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListarTodosActionPerformed
        MasajistaData md = new MasajistaData();
        List<Masajista> lista = md.listarMasajistasActivos();

        DefaultTableModel modelo = (DefaultTableModel) tablaMasajistas.getModel();
        modelo.setRowCount(0);

        for (Masajista m : lista) {
            modelo.addRow(new Object[]{
                m.getMatricula(),
                m.getNombreCompleto(),
                m.getTelefono(),
                m.getEspecialidad(),
                m.isEstado()
            });
        }
    }//GEN-LAST:event_jBListarTodosActionPerformed

    private void jBListarPorEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListarPorEspecialidadActionPerformed

        if (jCsEspecialidades.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una especialidad.");
            return;
        }

        String especialidad = jCsEspecialidades.getSelectedItem().toString();

        MasajistaData md = new MasajistaData();
        List<Masajista> lista = md.listarMasajistasPorEspecialidad(especialidad);

        // Preparar la tabla
        DefaultTableModel modelo = (DefaultTableModel) tablaMasajistas.getModel();
        modelo.setRowCount(0); // Limpiar la tabla

        // Cargar los datos en la tabla
        for (Masajista m : lista) {
            modelo.addRow(new Object[]{
                m.getMatricula(),
                m.getNombreCompleto(),
                m.getTelefono(),
                m.getEspecialidad(),
                m.isEstado()
            });
        }
    }//GEN-LAST:event_jBListarPorEspecialidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEspecialidad;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBListarPorEspecialidad;
    private javax.swing.JButton jBListarTodos;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBNuevoMasajista;
    private javax.swing.JComboBox<String> jCsEspecialidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox jcheckActivo;
    private javax.swing.JTable tablaMasajistas;
    private javax.swing.JTextField txtBuscarMatricula;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombreComp;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
