/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gr2_final.vistas;

import gr2_final.accesoadatos.ConsultorioData;
import gr2_final.accesoadatos.DiaDeSpaData;
import gr2_final.accesoadatos.MasajistaData;
import gr2_final.accesoadatos.SesionData;
import gr2_final.accesoadatos.TratamientoData;
import gr2_final.entidades.Consultorio;
import gr2_final.entidades.DiaDeSpa;
import gr2_final.entidades.Masajista;
import gr2_final.entidades.Sesion;
import gr2_final.entidades.Tratamiento;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import javax.swing.JOptionPane;

/**
 *
 * @author rodrigo
 */
public class SesionVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form SesionVista
     */
    public SesionVista() {
        initComponents();
        cargarComboTratamientos();
        cargarComboConsultorios();
        cargarComboMasajistas();
        cargarComboDiaDeSpa();
    }

    private void cargarComboTratamientos() {
        TratamientoData td = new TratamientoData();
        for (Tratamiento t : td.listarTratamientos()) {
            jCTratamiento.addItem(t);
        }
    }

    private void cargarComboConsultorios() {
        ConsultorioData cd = new ConsultorioData();
        for (Consultorio c : cd.listarConsultorios()) {
            jCConsultorio.addItem(c);
        }
    }

    private void cargarComboMasajistas() {
        MasajistaData md = new MasajistaData();
        for (Masajista m : md.listarMasajistasActivos()) {
            jCMasajista.addItem(m);
        }
    }

    private void cargarComboDiaDeSpa() {
        DiaDeSpaData dd = new DiaDeSpaData();
        jCDiadespa.addItem(null);
        for (DiaDeSpa d : dd.listarDiasDeSpa()) {
            jCDiadespa.addItem(d);
        }
    }

    private void limpiarCampos() {
        jTCodigo.setText("");

        jDCHoraInicio.setDate(null);
        jDCHoraFin.setDate(null);

        jCTratamiento.setSelectedIndex(0);
        jCConsultorio.setSelectedIndex(0);
        jCMasajista.setSelectedIndex(0);
        jCDiadespa.setSelectedIndex(0);

        jCBEstado.setSelected(true);

        jBModificar.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBGuardar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCBEstado = new javax.swing.JCheckBox();
        jCTratamiento = new javax.swing.JComboBox<Tratamiento>();
        jCConsultorio = new javax.swing.JComboBox<Consultorio>();
        jCMasajista = new javax.swing.JComboBox<Masajista>();
        jCDiadespa = new javax.swing.JComboBox<DiaDeSpa>();
        jDCHoraFin = new com.toedter.calendar.JDateChooser();
        jDCHoraInicio = new com.toedter.calendar.JDateChooser();
        jTCodigo = new javax.swing.JTextField();
        jBNuevo = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTBuscar = new javax.swing.JTextField();

        jLabel1.setText("Codigo Sesion");

        jLabel2.setText("Hora de Fin");

        jLabel3.setText("Hora de inicio");

        jLabel4.setText("Tratamiento");

        jLabel5.setText("Estado");

        jLabel6.setText("Dia de Spa");

        jLabel7.setText("Masajista");

        jLabel8.setText("Consultorio");

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");

        jLabel9.setText("Buscar por Codigo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jBNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCTratamiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCDiadespa, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCConsultorio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCMasajista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDCHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDCHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTCodigo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCBEstado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTBuscar)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(jBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jDCHoraInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDCHoraFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCDiadespa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jBNuevo)
                    .addComponent(jBModificar)
                    .addComponent(jBEliminar))
                .addContainerGap(342, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        jTCodigo.setText("");
        jDCHoraInicio.setDate(null);
        jDCHoraFin.setDate(null);

        jCTratamiento.setSelectedIndex(0);
        jCConsultorio.setSelectedIndex(0);
        jCMasajista.setSelectedIndex(0);
        jCDiadespa.setSelectedIndex(0);
        jCBEstado.setSelected(true);
        jBModificar.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBGuardar.setEnabled(true);
        jTCodigo.setEditable(false);
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        if (jDCHoraInicio.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una fecha de inicio.");
            return;
        }

        if (jDCHoraFin.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una fecha de fin.");
            return;
        }

        if (jCTratamiento.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un tratamiento.");
            return;
        }

        if (jCConsultorio.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un consultorio.");
            return;
        }

        if (jCMasajista.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un masajista.");
            return;
        }

        // DIA SPA es opcional
        DiaDeSpa pack = null;
        if (jCDiadespa.getSelectedIndex() > 0) {
            pack = (DiaDeSpa) jCDiadespa.getSelectedItem();
        }

    
    LocalDateTime inicio = jDCHoraInicio.getDate().toInstant()
            .atZone(ZoneId.systemDefault())
            .toLocalDate()
            .atStartOfDay();

    LocalDateTime fin = jDCHoraFin.getDate().toInstant()
            .atZone(ZoneId.systemDefault())
            .toLocalDate()
            .atStartOfDay();

        
        Tratamiento trat = (Tratamiento) jCTratamiento.getSelectedItem();
        Consultorio cons = (Consultorio) jCConsultorio.getSelectedItem();
        Masajista masaj = (Masajista) jCMasajista.getSelectedItem();

        boolean estado = jCBEstado.isSelected();

        
        Sesion s = new Sesion();
        s.setFechaHoraInicio(inicio);
        s.setFechaHoraFin(fin);
        s.setEstado(estado);
        s.setCodigoTratam(trat);
        s.setNroConsutorio(cons);
        s.setMatricula(masaj);
        s.setCodPack(pack);

        // GUARDAR SESIÓN
        SesionData sData = new SesionData();
        sData.guardarSesion(s);

        // MOSTRAR CODIGO GENERADO DE LA SESION EN JTCODIGO
        jTCodigo.setText(String.valueOf(s.getCodSesion()));

        jBModificar.setEnabled(true);
        jBEliminar.setEnabled(true);

        limpiarCampos();
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        
        /* if (jTCodigo.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Primero busque una sesión para modificar.");
        return;
    }

    if (jDCHoraInicio.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Seleccione una fecha de inicio.");
        return;
    }

    if (jDCHoraFin.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Seleccione una fecha de fin.");
        return;
    }

    if (jCTratamiento.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this, "Seleccione un tratamiento.");
        return;
    }

    if (jCConsultorio.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this, "Seleccione un consultorio.");
        return;
    }

    if (jCMasajista.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this, "Seleccione un masajista.");
        return;
    }

    // Día de spa — opcional
    DiaDeSpa pack = null;
    if (jCDiadespa.getSelectedIndex() > 0) {
        pack = (DiaDeSpa) jCDiadespa.getSelectedItem();
    }


    LocalDate inicio = jDCHoraInicio.getDate().toInstant()
            .atZone(ZoneId.systemDefault())
            .toLocalDate();

    LocalDate fin = jDCHoraFin.getDate().toInstant()
            .atZone(ZoneId.systemDefault())
            .toLocalDate();


    // TRAER OBJETOS SELECCIONADOS
    Tratamiento trat = (Tratamiento) jCTratamiento.getSelectedItem();
    Consultorio cons = (Consultorio) jCConsultorio.getSelectedItem();
    Masajista masaj = (Masajista) jCMasajista.getSelectedItem();

    boolean estado = jCBEstado.isSelected();


    Sesion s = new Sesion();
    s.setCodSesion(Integer.parseInt(jTCodigo.getText()));
    s.setFechaHoraInicio(inicio);
    s.setFechaHoraFin(fin);
    s.setEstado(estado);
    s.setCodigoTratam(trat);
    s.setNroConsutorio(cons);
    s.setMatricula(masaj);
    s.setCodPack(pack);

    // GUARDAR MODIFICACION
    SesionData sData = new SesionData();
    sData.modificarSesion(s);
    
    limpiarCampos();*/
    }//GEN-LAST:event_jBModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JCheckBox jCBEstado;
    private javax.swing.JComboBox<Consultorio> jCConsultorio;
    private javax.swing.JComboBox<DiaDeSpa> jCDiadespa;
    private javax.swing.JComboBox<Masajista> jCMasajista;
    private javax.swing.JComboBox<Tratamiento> jCTratamiento;
    private com.toedter.calendar.JDateChooser jDCHoraFin;
    private com.toedter.calendar.JDateChooser jDCHoraInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTBuscar;
    private javax.swing.JTextField jTCodigo;
    // End of variables declaration//GEN-END:variables
}
